---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluentd-aggregator
  namespace: fluentd
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: fluentd-aggregator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluentd
    version: 2.3.2
  values:
    # for log buffers
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi

    configmaps:
      output.conf: |
        <match **>
          @type null
        </match>
