---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluentd-aggregator
  namespace: fluentd
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: fluentd-aggregator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluentd
    version: 2.3.2
  values:
    # for log buffers
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi

    configmaps:
      output.conf: |
        <match **>
          @type stdout
          # <buffer>
          #   @type file
          #   path /var/log/fluentd-buffers/kubernetes.system.buffer
          #   flush_mode interval
          #   retry_type exponential_backoff
          #   flush_thread_count 2
          #   flush_interval 5s
          #   retry_forever
          #   retry_max_interval 30
          #   chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
          #   queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
          #   overflow_action block
          # </buffer>
        </match>
