---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: consul
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: consul
  chart:
    git: git@github.com:hashicorp/consul-helm.git
    ref: v0.14.0
    path: .
  values:
    # Choose an optional name for the datacenter
    global:
      datacenter: minidc
      dns:
        enabled: true
        clusterIP: "10.96.53.53"

    # Enable the Consul Web UI via a NodePort
    ui:
      service:
        type: 'NodePort'
        additionalSpec: |
          nodePort: 31002

    # Disable consul connect
    connectInject:
      enabled: false

    client:
      enabled: true
      grpc: true

    # Use only one Consul server for local development
    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        enabled: true
        maxUnavailable: 0

    # The catalog sync feature allows Consul to discover services deployed in Kubernetes, without an operator creating Consul registration files.
    syncCatalog:
      enabled: true

