---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.3.3
  values:
    prometheus:
      service:
        type: NodePort
        nodePort: 32005
    alertmanager:
      service:
        type: NodePort
        nodePort: 32006
    prometheusOperator:
      admissionWebhooks:
        patch:
          podAnnotations:
            "consul.hashicorp.com/connect-inject": "true"

