---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~4.0
    fluxcd.io/locked: "true"
    fluxcd.io/locked_msg: "Halt updates for now"
    fluxcd.io/locked_user: "Stefan Prodan <stefan@weave.works>"
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 10.2.1
  valueFileSecrets:
    # the redis-auth secret contains the password value
    - name: redis-auth
  values:
    usePassword: true
    cluster:
      enabled: false
