
---
version: 1
commandUpdated:
  generators:
    - command: |
        echo "---
        apiVersion: v1
        kind: Namespace
        metadata:
          labels:
            name: test-ns3
          name: test-ns3
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: helloworld
          namespace: test-ns3
        spec:
          selector:
            matchLabels:
              name: helloworld
          template:
            metadata:
              labels:
               name: helloworld
            spec:
              containers:
              - name: sleep
                image: gcr.io/google-containers/pause:3.1"
  updaters:
    - containerImage:
        command: echo uci $FLUX_WORKLOAD
      policy:
        command: echo ua $FLUX_WORKLOAD
